### ISSUE TITLE
Run document changes

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude-llm#120]
# What? 
We want to change how some things are done before start using provider logs

### TODO
- [ ] `documentLog` and last providerLog should be created synchronously after streaming is fininshed.
- [ ] `providerLog` should have a polymorphic nullable relation, either to `documentLog`, `evaluationResult`, or none.
- [ ] `documentLog` should know which of the `providerLog` that points to them is the latest step from the chain.
- [ ] `providerLog` should have a `timeUntilFirstToken` property.

**Comment by andresgutgon** [comment]
Doesn't makes sense now
