### ISSUE TITLE
Move editor dataset mappings to DB

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude-llm#720]
# What?
Now we persist dataset mapping of a prompt in Latitude Editor in local storage. 
![image](https://github.com/user-attachments/assets/b13061ca-ba8c-4478-b1ac-62d7e7dc0043)

We want to persist this mapping in DB. this way is shared between all the users in the workspace

## TODO

- [x] Move dataset mapping to the database as a JSONB in the document version table
- [x] Run in batch from editor does not persist the mapping 🐛 
- [x] Run in batch from evaluation does not persist the mapping 🐛 

### Run in batch from the editor
![image](https://github.com/user-attachments/assets/186e6672-c134-4764-b1b3-8ec6bde0a81d)

### Run in batch from evaluation
![image](https://github.com/user-attachments/assets/495df943-e98f-4cc3-b449-eacc373c6eb6)

**Comment by andresgutgon** [comment]
PR: https://github.com/latitude-dev/latitude-llm/pull/734
