### ISSUE TITLE
Move files from one folder to another in Sidebar

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude-llm#96]
# What?
We have to allow users to reorganize files. The same as with renaming files we need to take into account that moving a file or renaming it will possibly break others prompts that are referencing the moved file. 

## TODO
- [x] ~~Show modal warning when moving a file that can break things if we don't implement auto update references~~ Not doing for now
- [x] ~~Think if it's possible to auto-updated references cc @csansoon~~ Complicated. Not doing for now
- [x] Implement drag & drop in sidebar `#fun`

**Comment by samulatitude** [comment]
I'd try to reduce the scope here, if the modal showing a warning is much easier, I'd go with that. 

Anyway, an idea for the autoupdate is that if we don't use the full path, just the name, we could search for that file at any level by default. The problem would be two files with the same name, but I'm not sure if that would be a common case 🤔 (probably will cause us problems xD)

**Comment by andresgutgon** [comment]
> probably will cause us problems

Yes, if we do this we have to do it perfectly right. Otherwise better do nothing and show the warning
